#! /bin/sh

### Key Bindings

## allow the use of the Delete/Insert keys
## the following line is actually equivalent to "\C-?": delete-char
"\e[3~": delete-char
"\e[2~": quoted-insert

## VT
## allow the use of the Home/End keys
"\e[1~": beginning-of-line
"\e[4~": end-of-line
## mappings for "page up" and "page down" to step to the beginning/end
## of the history
"\e[5~": beginning-of-history
"\e[6~": end-of-history
## alternate mappings for "page up" and "page down" to search the history
#"\e[5~": history-search-backward
#"\e[6~": history-search-forward

## rxvt and konsole (i.e. the KDE-app...)
"\e[7~": beginning-of-line
"\e[8~": end-of-line

## kvt/Konsole
"\e[H": beginning-of-line
"\e[F": end-of-line

## VT220/xterm
"\eOH": beginning-of-line
"\eOF": end-of-line

## mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving
#"\e[5C": forward-word
#"\e[5D": backward-word
#"\e\e[C": forward-word
#"\e\e[D": backward-word

## All of the following map the escape sequence of the
## value contained inside the 1st argument to the
## readline specific functions
"\eOd": backward-word
"\eOc": forward-word

## Application keypad and cursor of xterm
"\eOD": backward-char
"\eOC": forward-char
"\eOA": previous-history
"\eOB": next-history
"\eOE": re-read-init-file

## Allow 8-bit input/output
#set meta-flag on
#set convert-meta off
#set input-meta on
#set output-meta on

## vi like mode
# set editing-mode vi

## Allow the command prompt to wrap to the next line
set horizontal-scroll-mode Off

# $if Bash
    ## Don't ring bell on completion
    set bell-style none

    ## or, don't beep at me - show me
    # set bell-style visible

    ## Filename completion/expansion
    set completion-ignore-case on
    set show-all-if-ambiguous on

    ## Expand homedir name
    # set expand-tilde on

    ## Append "/" to all dirnames : on/off
    set mark-directories on
    # set mark-modified-lines on
    set mark-symlinked-directories on

    ## Match all files
    set match-hidden-files on
    ## Show all if ambigious
    set show-all-if-ambiguous on
    ## bash completions does not use more
    set page-completions off

    ## 'Magic Space'
    ## Insert a space character then performs
    ## a history expansion in the line
    #Space: magic-space
# $endif

## Macros