#! /bin/bash
# Easiser for navigation
alias ..="cd .."
# alias ...="cd ../.."
# alias ....="cd ../../.."
# alias .....="cd ../../../.."
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"
## get rid of command not found ##
alias cd..='cd ..'

# Some shortcuts for different directory listings
alias ls='ls -hF --color=auto'                # classify files in colour
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -alF'                            # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'

# Enable aliases to be sudo’ed
alias sudo='sudo '

alias mkdir='mkdir -pv'

# Shortcuts
# alias d="cd ~/Documents/Dropbox"
alias p="\cd ~/projects "
alias g="\git "
alias h="\history "
# jobs alias
alias j='\jobs -l'
# editor
alias v="\vim"
alias vim='\vim '
alias gv='\gvim '
alias e="\vim"
# alias s="subl ."
# alias o="open"
# alias oo="open ."

# alias t="top"
alias t="htop"

# clear
alias c='clear '
alias clr='clear '

# screen command
alias scr='screen'
alias scrls='screen -ls'
alias scrra='screen -r'
alias scrrd='screen -rd'

# tmux command
# alias tmux='~/bin/tmux ' # tmux path
alias ta='tmux attach -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'

# ssh
alias sshx="ssh -X "

# tree
alias tree="tree -C "
alias tree1='tree -L 1 '
alias tree2='tree -L 2 '
alias tree3='tree -L 3 '

alias tr1='tree -L 1 -p '
alias tr2='tree -L 2 -p '
alias tr3='tree -L 3 -p '

# ctags
alias ctags="/usr/bin/ctags "
alias erlctags="ctags --file-scope=no -R --languages=erlang "
alias etags="~/tools/bin/ctags "
alias erltags="etags --file-scope=no -R --languages=erlang "

# cmake
# alias cmake="~/tools/cmake/cmake-3.0.1/bin/cmake"
#


# ack
# alias ack="~/tools/ack/ack --color "
alias ack="ack --color "

# ag
# alias ag="~/tools/ag/ag --color --ignore '*tags' "
alias ag="ag --color --ignore '*tags' "

# path jump helper
# autojump
# [[ -s /home/eijjmno/.autojump/etc/profile.d/autojump.sh  ]] && source /home/eijjmno/.autojump/etc/profile.d/autojump.sh

