#!/usr/bin/bash
# This is a generic bash rc file
#
#

 # 256 color settings
 if [ -e /usr/share/terminfo/x/xterm-256color  ]; then
     #debian在/lib/terminfo/x/xterm-256color
     export TERM='xterm-256color'
 else
     export TERM='xterm-color'
 fi
