#! /bin/bash

#!/usr/bin/env bash
### bash file
### configuration for the mac bashrc
###

export PAGER="most"
export EDITOR="vim"

## Bash Aliases
if [ -f "${HOME}/.bash_aliases" ]; then
   source "${HOME}/.bash_aliases"
fi

## Easiser for navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

## get rid of command not found ##
alias cd..='cd ..'

## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

## shortcut 
alias c='clear'
alias g="git"
alias v="vim"
# editor settings
alias e="/Users/chaozhao/homebrew/Cellar/vim/7.4.488/bin/vim"
# alias e="vim"

alias h='history'
alias j='jobs -l'

alias ls="ls -G" 
alias ll="ls -alF"
alias la="ls -A"
alias l="ls -CF"

alias clr="clear"

